addSbtPlugin("com.github.sbt" % "sbt-release" % "1.0.15")
addSbtPlugin("com.github.sbt" % "sbt-pgp" % "2.1.2")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.10.0")
//addSbtPlugin("com.geirsson" % "sbt-ci-release" % "1.5.5")
//addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
